version: '2'
services:
    app:
        build: docker/local/.
        volumes:
            - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/local/php/php.ini:/usr/local/etc/php/php.ini
            - .:/var/www/app
        depends_on:
            - database
            - redis
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            APP_ENVIRONMENT: '${APP_ENV}'
            CONTAINER_ROLE: app
    database:
        image: mariadb/server:10.3
        volumes:
            - ./docker-data/mariadb:/var/lib/mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
    tarantool:
        image: tarantool/tarantool:latest
        volumes:
            - ./docker-data/tarantool:/opt/tarantool
            - ./docker-data/tarantool/files:/var/lib/tarantool
        ports:
            - '${FORWARD_TARANTOOL_PORT:-3301}:3301'
        environment:
            TARANTOOL_USER_NAME: '${DB_TARANTOOL_USERNAME}'
            TARANTOOL_USER_PASSWORD: '${DB_TARANTOOL_PASSWORD}'
            TARANTOOL_MEMTX_MEMORY: 1073741824
            TARANTOOL_CHECKPOINT_INTERVAL: 900
    tarantool-admin:
        image: quay.io/basis-company/tarantool-admin
        ports:
            - 3302:80
    redis:
        image: redis:4.0.14-alpine
        environment:
            REDIS_PASSWORD: '${REDIS_PASSWORD}'
