<?php

namespace App\Services\Payment;

use App\Services\Payment\Providers\Paybox\PayboxServiceProvider;
use Illuminate\Support\ServiceProvider;

class PaymentServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind('paymentService', PaymentService::class);
        $this->app->register(PayboxServiceProvider::class);
    }
}
