<?php

namespace App\Services\Payment\Providers\OneVision;

use Carbon\Laravel\ServiceProvider;

class OneVisionServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind('oneVisionService', function () {
            return new OneVisionService(new OneVisionRepository);
        });
    }
}
