<?php

namespace App\Http\Controllers\Admin;

class BlockCrudController extends BaseCrudController
{
    protected bool $hasReorderOperation = true;

    protected function setupReorderOperation($field = 'title')
    {
        parent::setupReorderOperation($field); // TODO: Change the autogenerated stub
    }
}
