<?php

namespace App\Http\Controllers\Admin;

class CategoryCrudController extends BaseCrudController
{
    protected bool $hasReorderOperation = true;

    protected function setupCreateOperation()
    {
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name'      => 'parent',
            'type'      => 'select2',
            'attribute' => 'name',
            'label'     => trans('admin.category.relations.parent'),
        ]);
    }

    protected function setupUpdateOperation()
    {
        parent::setupUpdateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name'      => 'parent',
            'type'      => 'select2',
            'attribute' => 'name',
            'label'     => trans('admin.category.relations.parent'),
            'options'   => fn($query) => $query
                ->where('id', '!=', $this->crud->getCurrentEntry()->id)
                ->get()
        ]);
        $this->crud->addField([
            'name'      => 'subcategories',
            'type'      => 'select2_multiple',
            'attribute' => 'name',
            'label'     => trans('admin.category.relations.subcategories'),
            'options'   => fn($query) => $query
                ->whereDoesntHave('parent')
                ->where('id', '!=', $this->crud->getCurrentEntry()->id)
                ->get()
        ]);
    }

    protected function setupShowOperation()
    {
        parent::setupShowOperation(); // TODO: Change the autogenerated stub
        $this->crud->addColumn([
            'name'      => 'parent',
            'type'      => 'select',
            'attribute' => 'name',
            'label'     => trans('admin.category.relations.parent'),
        ]);
        $this->crud->addColumn([
            'name'      => 'subcategories',
            'type'      => 'select',
            'attribute' => 'name',
            'label'     => trans('admin.category.relations.subcategories')
        ]);
    }
}
