<?php

namespace App\Http\Controllers\Admin;

class MarketCrudController extends BaseCrudController
{
    protected bool $hasReorderOperation = true;

    protected function setupUpdateOperation()
    {
        parent::setupUpdateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name'      => 'cities',
            'type'      => 'select2_multiple',
            'attribute' => 'name',
            'label'     => trans('admin.city.plural'),
            'allows_null' => false,
        ]);
        $this->crud->addField([
            'name'      => 'categories',
            'type'      => 'select2_multiple',
            'attribute' => 'name',
            'label'     => trans('admin.category.plural'),
            'allows_null' => false,
            'options'   => fn($query) => $query
                ->whereNull('parent_id')
                ->where('is_active', true)
                ->get()
        ]);
    }
}
