<?php

namespace App\Http\Controllers\Admin;

class ProductCrudController extends BaseCrudController
{
    protected bool $hasReorderOperation = true;

    protected function setupUpdateOperation()
    {
        parent::setupUpdateOperation(); // TODO: Change the autogenerated stub
        $this->setupDescriptionField();
    }

    private function setupDescriptionField() {
        $this->crud->addField([
            'name' => 'productDescription',
            'label' => trans('admin.product_description.fields.description'),
            'type' => 'ckeditor',
            'attributes' => [
                'readonly' => 'readonly'
            ],
        ]);
        $description = $this->crud->getCurrentEntry()->description;
        if ($description) {
            $url = route('product_description.edit', ['id' => $description->id]);
        } else {
            $url = route('product_description.create');
        }
        $this->crud->addField([   // CustomHTML
            'name'  => 'separator',
            'type'  => 'custom_html',
            'value' => '<a href="'
                . $url .
                '" target="_blank" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">Редактировать описание</a>'
        ]);
    }
}
