<?php

namespace App\Http\Controllers\Admin;

class ProductDescriptionCrudController extends BaseCrudController
{
    public function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub
    }

    protected function setupListOperation()
    {
        parent::setupListOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name' => 'description',
            'label' => trans('admin.description'),
            'type' => 'ckeditor',
            'attributes' => [
                'readonly' => 'readonly'
            ],
        ]);
    }

    protected function setupCreateOperation()
    {
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name' => 'description',
            'label' => trans('admin.product_description.fields.description'),
            'type' => 'ckeditor',
        ]);
    }
}
