<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Models\PromotionGroup;

class PromotionGroupCategoryCrudController extends BaseCrudController
{
    protected bool $hasReorderOperation = true;

    protected function setupListOperation()
    {
        parent::setupListOperation(); // TODO: Change the autogenerated stub
        $this->crud->addColumn([
            'name'      => 'promotion_group_id',
            'type'      => 'select',
            'entity'    => 'promotionGroup',
            'attribute' => 'name',
            'label'     => trans('admin.promotion_group.singular'),
        ]);
        $this->crud->addColumn([
            'name'      => 'category_id',
            'type'      => 'select',
            'entity'    => 'category',
            'attribute' => 'name',
            'label'     => trans('admin.category.singular'),
        ]);
    }

    protected function setupCreateOperation()
    {
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name'      => 'promotion_group_id',
            'model'     => PromotionGroup::class,
            'entity'    => 'promotionGroup',
            'type'      => 'select2',
            'attribute' => 'name',
            'label'     => trans('admin.promotion_group.singular'),
        ]);
        $this->crud->addField([
            'name'      => 'category_id',
            'model'     =>  Category::class,
            'entity'    => 'category',
            'type'      => 'select2',
            'label'     => trans('admin.category.singular'),
            'placeholder' => "Выберите категорию",
        ]);
    }
}
