<?php

namespace App\Http\Controllers\Admin;

use App\Models\Product;
use App\Models\PromotionGroup;

class PromotionGroupProductCrudController extends BaseCrudController
{
    protected bool $hasReorderOperation = true;

    protected function setupListOperation()
    {
        parent::setupListOperation(); // TODO: Change the autogenerated stub
        $this->crud->addColumn([
            'name'      => 'promotion_group_id',
            'type'      => 'select',
            'entity'    => 'promotionGroup',
            'attribute' => 'name',
            'label'     => trans('admin.promotion_group.singular'),
        ]);
        $this->crud->addColumn([
            'name'      => 'product_id',
            'type'      => 'select',
            'entity'    => 'product',
            'attribute' => 'name',
            'label'     => trans('admin.product.singular'),
        ]);
    }

    protected function setupCreateOperation()
    {
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name'      => 'promotion_group_id',
            'model'     => PromotionGroup::class,
            'entity'    => 'promotionGroup',
            'type'      => 'select2',
            'attribute' => 'name',
            'label'     => trans('admin.promotion_group.singular'),
        ]);
        $this->crud->addField([
            'name'      => 'product_id',
            'model'     =>  Product::class,
            'entity'    => 'product',
            'type'      => 'select2_from_ajax',
            'label'     => trans('admin.product.singular'),
            'data_source' => url('api/admin/products'),
            'delay' => 500,
            'minimum_input_length' => 2,
            'placeholder' => "Выберите продукт",
        ]);
    }
}
