<?php

namespace App\Http\Controllers\Admin;

use App\Models\Rating;

class RatingMessageCrudController extends BaseCrudController
{
    protected bool $hasReorderOperation = true;

    public function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub
        $this->setupFilters();
    }

    protected function setupListOperation()
    {
        parent::setupListOperation(); // TODO: Change the autogenerated stub
        $this->crud->addColumn([
            'name'      => 'rating',
            'type'      => 'select2',
            'attribute' => 'rating',
            'label'     => trans('admin.rating_message.relations.rating'),
            'allows_null' => false,
        ]);
    }

    protected function setupCreateOperation()
    {
        $this->crud->addField([
            'name'      => 'rating',
            'type'      => 'select2',
            'attribute' => 'rating',
            'label'     => trans('admin.rating_message.relations.rating'),
            'allows_null' => false,
        ]);
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
    }

    private function setupFilters() {
        $this->crud->addFilter([
            'name' => 'rating',
            'label' => trans('admin.rating_message.relations.rating'),
            'type' => 'select2',
        ], function() {
            return Rating::query()->get()->pluck('rating', 'id')->toArray();
        }, function($value) {
                $this->crud->addClause('whereHas', 'rating', function ($query) use ($value) {
                    $query->where('rating', $value);
                });
        });
    }
}
