<?php

namespace App\Http\Controllers\Admin;

class UserCrudController extends BaseCrudController
{
    protected function setupCreateOperation()
    {
        parent::setupCreateOperation(); // TODO: Change the autogenerated stub
        $this->crud->addField([
            'name'      => 'roles',
            'type'      => 'select2_multiple',
            'attribute' => 'ru_name',
            'label'     => trans('admin.role.singular'),
        ]);
    }
}
